# 베이스 이미지 설정
FROM openjdk:17-jdk-alpine

# 애플리케이션 JAR 파일을 빌드 컨테이너로 복사 및 빌드
WORKDIR /app

COPY gradle gradle
COPY build.gradle settings.gradle ./
COPY src src

# Gradle Wrapper 다운로드 및 빌드
RUN ./gradlew build --no-daemon

# 빌드된 JAR 파일을 복사
COPY build/libs/backend-0.0.1-SNAPSHOT.jar app.jar

# 애플리케이션 실행
ENTRYPOINT ["java","-jar","/app.jar"]

# 필요한 포트 개방
EXPOSE 8080